import { Word } from '../types/word.types';

export const INITIAL_WORDS: Word[] = [
  {
    id: 'w-1',
    word: 'Ephemeral',
    meaning: 'Lasting for a very short time; transitory.',
    example: 'The ephemeral beauty of cherry blossoms draws millions of visitors every spring.',
    category: 'Academic',
    difficulty: 'Hard',
    createdAt: '2026-01-10T10:00:00.000Z',
    updatedAt: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'w-2',
    word: 'Eloquent',
    meaning: 'Fluent or persuasive in speaking or writing.',
    example: 'Her eloquent speech moved the entire audience to tears.',
    category: 'Literature',
    difficulty: 'Medium',
    createdAt: '2026-01-11T11:00:00.000Z',
    updatedAt: '2026-01-11T11:00:00.000Z',
  },
  {
    id: 'w-3',
    word: 'Resilient',
    meaning: 'Able to withstand or recover quickly from difficult conditions.',
    example: 'The team remained resilient despite facing numerous unexpected setbacks.',
    category: 'General',
    difficulty: 'Easy',
    createdAt: '2026-01-12T12:00:00.000Z',
    updatedAt: '2026-01-12T12:00:00.000Z',
  },
  {
    id: 'w-4',
    word: 'Pragmatic',
    meaning: 'Dealing with things sensibly and realistically in a practical way.',
    example: 'We need a pragmatic solution to solve the traffic congestion problem.',
    category: 'Business',
    difficulty: 'Medium',
    createdAt: '2026-01-13T13:00:00.000Z',
    updatedAt: '2026-01-13T13:00:00.000Z',
  },
  {
    id: 'w-5',
    word: 'Ubiquitous',
    meaning: 'Present, appearing, or found everywhere.',
    example: 'Smartphones have become ubiquitous in modern urban societies.',
    category: 'Technology',
    difficulty: 'Hard',
    createdAt: '2026-01-14T14:00:00.000Z',
    updatedAt: '2026-01-14T14:00:00.000Z',
  },
  {
    id: 'w-6',
    word: 'Meticulous',
    meaning: 'Showing great attention to detail; very careful and precise.',
    example: 'The researcher maintained meticulous records of all experimental procedures.',
    category: 'Science',
    difficulty: 'Medium',
    createdAt: '2026-01-15T15:00:00.000Z',
    updatedAt: '2026-01-15T15:00:00.000Z',
  },
  {
    id: 'w-7',
    word: 'Serendipity',
    meaning: 'The occurrence and development of events by chance in a happy or beneficial way.',
    example: 'Finding my current business partner at that random conference was pure serendipity.',
    category: 'Literature',
    difficulty: 'Hard',
    createdAt: '2026-01-16T16:00:00.000Z',
    updatedAt: '2026-01-16T16:00:00.000Z',
  },
  {
    id: 'w-8',
    word: 'Innovative',
    meaning: 'Featuring new methods; advanced and original.',
    example: 'The startup introduced an innovative method for recycling plastic waste.',
    category: 'Technology',
    difficulty: 'Easy',
    createdAt: '2026-01-17T17:00:00.000Z',
    updatedAt: '2026-01-17T17:00:00.000Z',
  },
  {
    id: 'w-9',
    word: 'Comprehensive',
    meaning: 'Complete; including all or nearly all elements or aspects of something.',
    example: 'The report provided a comprehensive analysis of the quarterly economic trends.',
    category: 'Academic',
    difficulty: 'Easy',
    createdAt: '2026-01-18T18:00:00.000Z',
    updatedAt: '2026-01-18T18:00:00.000Z',
  },
  {
    id: 'w-10',
    word: 'Paradigm',
    meaning: 'A typical example or pattern of something; a model or conceptual framework.',
    example: 'Quantum computing represents a major paradigm shift in computer science.',
    category: 'Science',
    difficulty: 'Hard',
    createdAt: '2026-01-19T19:00:00.000Z',
    updatedAt: '2026-01-19T19:00:00.000Z',
  },
  {
    id: 'w-11',
    word: 'Itinerary',
    meaning: 'A planned route or journey with a detailed timetable.',
    example: 'We checked our travel itinerary to confirm the departure time for the morning flight.',
    category: 'Travel',
    difficulty: 'Easy',
    createdAt: '2026-01-20T20:00:00.000Z',
    updatedAt: '2026-01-20T20:00:00.000Z',
  },
  {
    id: 'w-12',
    word: 'Lucid',
    meaning: 'Expressed clearly; easy to understand; having a clear mind.',
    example: 'The professor gave a lucid explanation of a very complex thermodynamic principle.',
    category: 'Academic',
    difficulty: 'Medium',
    createdAt: '2026-01-21T21:00:00.000Z',
    updatedAt: '2026-01-21T21:00:00.000Z',
  },
];
